# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_request_method_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBenchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='time')),
                ('description', models.CharField(max_length=255)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
        ),
    ]
